### PR TITLE
updated to OpenZeppelin v3 and solc ^0.6.0

### PR DESCRIPTION
**Pull request by naszam**

### CODE REVIEW

**Comment by naszam** [comment]
Added .gitattributes file with solidity language syntax highlighting

**Comment by naszam** [comment]
Updated Migrations.sol to solc v.0.5.0.
Commented truffle-config.js relative to hdwallet-provider.

**Comment by naszam** [comment]
Updated to OpenZeppelin v3.0.0 and solc ^0.6.0.

I've commented some changes, like toString() already included in OpenZeppelin /utils/Strings.sol, 
Minter Role added using AccessControl.sol, transfer functions overridden using some code from ERC721Pausable.sol, setting the require to !true, .length-- to pop() as described in the docs, ...
Added also an updated truffle-config.js and updated Migration.sol to solc ^0.6.0.

The only issue is that the code size exceeds the limit introduced in Spurious Dragon:
```
open-proofs/contracts/Badges/Badges.sol:9:1: Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
```

**Comment by naszam** [comment]
Clean up

**Comment by rrecuero** [comment]
You probably don't need to commit both truffle-config files. The . file shouldn't be added to the repo

**Comment by naszam** [comment]
Just fixed that!

**Pull request merged**
